// MUAC Worker
// Public entrypoint that delegates requests to the OpenNext worker.

interface RateLimitBinding {
  limit(options: { key: string }): Promise<{ success: boolean }>;
}

interface Env {
  ANALYTICS_RATE_LIMITER: RateLimitBinding;
}

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ) {
    try {
      const url = new URL(request.url);

      /*
       * Rate limiting do endpoint público de analytics.
       *
       * O POST /api/analytics precisa continuar público,
       * pois é utilizado pelos visitantes do site.
       *
       * O limite é aplicado antes da requisição chegar ao OpenNext/D1.
       */
      const isAnalyticsPost =
        request.method === "POST" &&
        url.pathname === "/api/analytics";

      if (isAnalyticsPost) {
        const clientIp =
          request.headers.get("CF-Connecting-IP") ?? "unknown";

        const rateLimitKey = `analytics:${clientIp}`;

        const { success } =
          await env.ANALYTICS_RATE_LIMITER.limit({
            key: rateLimitKey,
          });

        if (!success) {
          return new Response(
            JSON.stringify({
              error: "Too many analytics requests.",
            }),
            {
              status: 429,
              headers: {
                "Content-Type": "application/json; charset=utf-8",
                "Cache-Control": "no-store",
                "Retry-After": "60",
              },
            },
          );
        }
      }

      // @ts-ignore - generated by OpenNext during build
      const openNextMod = await import("./.open-next/worker.js");
      const openNextAny = openNextMod as any;

      if (
        openNextAny &&
        openNextAny.default &&
        typeof openNextAny.default.fetch === "function"
      ) {
        return await openNextAny.default.fetch(
          request,
          env,
          ctx,
        );
      }

      if (
        openNextAny &&
        typeof openNextAny.fetch === "function"
      ) {
        return await openNextAny.fetch(
          request,
          env,
          ctx,
        );
      }

      throw new Error(
        "OpenNext generated worker missing fetch",
      );
    } catch (error) {
      console.error(
        "OpenNext delegation error:",
        error,
      );

      return new Response("Internal Server Error", {
        status: 500,
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
        },
      });
    }
  },
};